apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
  labels:
    app: mongodb
spec:
  replicas: 3                          # 3 pods for Replica Set
  serviceName: "mongodb-headless"      # must match Headless Service name
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10     # gracefully shutdown pods when scaling down
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent       # use local image if exists, skip pulling
        command:
        - mongod
        - "--replSet"                       # enable Replica Set mode
        - "rs0"                             # replica set name — must match Job
        - "--bind_ip_all"                   # accept connections from all IPs inside cluster
        - "--auth"                          # enable authentication
        - "--keyFile=/etc/mongodb/keyfile"  # required when --auth + --replSet are used together
        ports:
          - containerPort: 27017            # default MongoDB port
        volumeMounts:
          - mountPath: /data/db             # persistent data storage
            name: mongodb-vol
          - mountPath: /etc/mongodb/keyfile # keyFile mounted as single file from Secret
            name: mongodb-keyfile
            subPath: keyfile                # mount only this key from Secret, not entire Secret

        env:
        - name: MONGO_INITDB_ROOT_USERNAME  # root username from secret
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD  # root password from secret
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE       # initial database name to create
          value: "hoteldb"

        readinessProbe:
          tcpSocket:
            port: 27017                     # Is it possible to open a TCP connection
          periodSeconds: 10                 # check every 5s
          timeoutSeconds: 5                 # fail if no response in 5s

      volumes:
      - name: mongodb-keyfile               # shared secret key for inter-node auth in Replica Set
        secret:
          secretName: mongodb-secret
          defaultMode: 0400                 # MongoDB requires strict 400 permissions on keyFile
          items:
          - key: keyfile
            path: keyfile
                    
  volumeClaimTemplates:                     # auto-creates PVC for each pod
  - metadata:
      name: mongodb-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]      # single node read-write
      resources:
        requests:
          storage: 500Mi