apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-frontend-agent
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-front-slv
  template:
    metadata:
      labels:
        app: jenkins-front-slv
    spec:
      # securityContext:
      #       fsGroup: 1000 
      #       runAsUser: 1000
      # serviceAccountName: jenkins-admin
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
        - name: jenkins-frontend-agent
          image: nexus-service.nexus-ns.svc.cluster.local:8083/jenkins-inbound-agent-image:latest
          imagePullPolicy: Always # Always pull # IfNotPresent # use local image if exists, skip pulling

          env:
          # From Secret
          - name: JENKINS_URL                   # 
            valueFrom:
              secretKeyRef:
                name: jenkins-frontend-secret
                key: JENKINS_URL
          - name: JENKINS_SECRET                   # 
            valueFrom:
              secretKeyRef:
                name: jenkins-frontend-secret
                key: JENKINS_SECRET 
          - name: JENKINS_AGENT_NAME                   # 
            valueFrom:
              secretKeyRef:
                name: jenkins-frontend-secret
                key: JENKINS_AGENT_NAME   
          - name: JENKINS_TUNNEL          
            value: "jenkins-service:50000" # jnlp port Jenkins master