# DNS server 1 — Cluster CoreDNS, Knows all K8S services. 
# To check: kubectl get svc kube-dns -n kube-system
nameserver 10.96.0.10
# DNS server 2 — External DNS (Docker Desktop) for backup, For external addresses (google.com, etc.). 
# To check docker exec kind-01-worker cat /etc/resolv.conf | grep nameserver
nameserver 192.168.65.254
# How many dots are in the name before using search
options ndots:5
search default.svc.cluster.local svc.cluster.local cluster.local
