apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-srv
  template:
    metadata:
      labels:
        app: jenkins-srv
    spec:
      # securityContext:
      #       fsGroup: 1000 
      #       runAsUser: 1000
      serviceAccountName: jenkins-admin

      
      # initContainer installs plugins BEFORE jenkins starts
      initContainers:
        - name: install-plugins
          image: jenkins/jenkins:lts-jdk21
          command:
            - jenkins-plugin-cli
            - --plugins
            - "kubernetes generic-webhook-trigger workflow-aggregator git github configuration-as-code"
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
          resources:
            requests:
              cpu: "200m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home


      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk21
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: "-Xms512m -Xmx1g -XX:+UseG1GC"  # mem for JVM from 512mb-2gb
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnl-pport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home   

  volumeClaimTemplates:                     # auto-creates PVC for each pod
  - metadata:
      name: jenkins-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]      # single node read-write
      resources:
        requests:
          storage: 1Gi