apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "backend-role"
        vault.hashicorp.com/agent-inject-secret-mongodb.env: "secret/data/mongodb"
        vault.hashicorp.com/agent-inject-template-mongodb.env: |
          {{- with secret "secret/data/mongodb" -}}
          export DB_ReadWrite_User="{{ .Data.data.DB_ReadWrite_User }}"
          export DB_ReadWrite_Pass="{{ .Data.data.DB_ReadWrite_Pass }}"
          export DB_ReadOnly_User="{{ .Data.data.DB_ReadOnly_User }}"
          export DB_ReadOnly__Pass="{{ .Data.data.DB_ReadOnly__Pass }}"
          {{- end }}
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
      - name: backend-container
        image: nexus-service.nexus-ns.svc.cluster.local:8083/backend-image:8d6e637ed7d40f96ec90c0ad87c2ef0702aed55e
        imagePullPolicy: Always # Always pull # IfNotPresent # use local image if exists, skip pulling
        command: ["/bin/sh", "-c"]
        args:
          - |
            source /vault/secrets/mongodb.env
            exec python app_backend.py

        ports:
        - containerPort: 5000

        env:
        # From ConfigMap    
        - name: DB_CONNECT_STR
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_CONNECT_STR 
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_PORT                                    

        envFrom:
        # All keys from app-config become environment variables
        - configMapRef:
            name: backend-cm