apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: nexus-ns
  labels:
    app: nexus-srv
spec:
  replicas: 1                          # 3 pods for Replica Set
  selector:
    matchLabels:
      app: nexus-srv
  template:
    metadata:
      labels:
        app: nexus-srv
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        imagePullPolicy: IfNotPresent       # use local image if exists, skip pulling
        ports:
          - containerPort: 8081             # default UI Nexus port
          - containerPort: 8083             # Docker registry
        volumeMounts:
          - mountPath: /nexus-data          # persistent data storage
            name: nexus-vol

      #   env:
      #   - name: MONGO_INITDB_ROOT_USERNAME  # root username from secret
      #     valueFrom:
      #       secretKeyRef:
      #         name: mongodb-secret
      #         key: username
      #   - name: MONGO_INITDB_ROOT_PASSWORD  # root password from secret
      #     valueFrom:
      #       secretKeyRef:
      #         name: mongodb-secret
      #         key: password
      #   - name: MONGO_INITDB_DATABASE       # initial database name to create
      #     value: "hoteldb"

      #   readinessProbe:                     # checks if pod is ready to receive traffic
      #     exec:
      #       command:
      #         - mongosh
      #         - --eval
      #         - "db.adminCommand('ping')"
      #     initialDelaySeconds: 5           # wait 5s after start before first check
      #     periodSeconds: 5                 # check every 5s
      #     timeoutSeconds: 3                # fail if no response in 3s
      #     successThreshold: 1              # 1 success = ready
      #     failureThreshold: 6              # 6 failures = not ready, remove from Service

      # volumes:
      # - name: mongodb-keyfile               # shared secret key for inter-node auth in Replica Set
      #   secret:
      #     secretName: mongodb-secret
      #     defaultMode: 0400                 # MongoDB requires strict 400 permissions on keyFile
      #     items:
      #     - key: keyfile
      #       path: keyfile
                    
  volumeClaimTemplates:                     # auto-creates PVC for pod
  - metadata:
      name: nexus-vol                     
    spec:
      accessModes: [ "ReadWriteOnce" ]      # single node read-write
      resources:
        requests:
          storage: 1Gi                    # 10Gi , 500Mi