apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-srv
  template:
    metadata:
      labels:
        app: jenkins-srv
    spec:
      # securityContext:
      #       fsGroup: 1000 
      #       runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk21
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: "-Xmx2g -Xms512m -XX:+UseG1GC"  # mem for JVM from 512mb-2gb
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnl-pport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home   

  volumeClaimTemplates:                     # auto-creates PVC for each pod
  - metadata:
      name: jenkins-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]      # single node read-write
      resources:
        requests:
          storage: 1Gi