apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
  namespace: frontend
data:
  config.js: |
    window.APP_CONFIG = {
      API_URL: '/api',
      APM_ENABLED: true,
      APM_SERVER_URL: 'http://localhost:8200'
### kubectl port-forward -n monitoring svc/apm-server-apm-server 8200:8200
    }

