apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
      - name: frontend-container
        # image: backend-image:latest
        image: nexus-service.nexus-ns.svc.cluster.local:8083/frontend-image:01708559f54228d2ffe2c7a521f0ba63c5d83730
        imagePullPolicy: Always # Always pull # IfNotPresent # use local image if exists, skip pulling
        ports:
        - containerPort: 80 # 3000
                           
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config.js
          name: config-js
          subPath: config.js

      volumes:
      - name: config-js
        configMap:
          name: frontend-cm
          items:
          - key: config.js
            path: config.js